import { KibanResponse } from '@types';

export interface RequestBody {
    encabezado: {
        productoRequerido: string,
        tipoResponsabilidad: string,
        tipoContrato: string,
        claveUsuario: string,
        contrasenaUsuario: string,
        numeroReferenciaOperador: string,
        importeContrato: number,
        monedaCredito: string,
        idioma: string
    },
    nombre: {
        apellidoPaterno: string,
        apellidoMaterno: string,
        primerNombre: string,
        segundoNombre: string,
        rfc: string,
    },
    domicilio: {
        direccion: {
            direccion: string,
            cp: string,
        }
    }
}

export interface apiData {
    url: string,
    duration: number,
    request: {
        date: Date,
        body: string,
    },
    response: {
        date: Date,
        body: string
    }
}

// interface Response extends KibanResponse {
//     apiData: apiData[],
//     response: {
//         consultasEfectudas: [{
//            claveOtorgante: string,
//            claveUnidadMonetaria: string,
//            consumidorNuevo: string,
//            fechaConsulta: Date,
//            identificacionBuro: string,
//            importeContrato: number, // Defaults to 0
//            indicadorTipoResponsabilidad: string,
//            nombreOtorgante: string,
//            telefonoOtorgante: string,
//            tipoContrato: string,           
//         }],
//         cuentas: [{
//             claveObservacion: string,
//             claveOtorgante: string,
//             claveUnidadMonetaria: string,
//             creditoMaximo: number,
//             fechaActualizacion: Date,
//             fechaAperturaCuenta: Date,
//             fechaCancelacionCAN: Date,
//             fechaCierreCuenta: Date,
//             fechaHistoricaMorosidadMasGrave: Date,
//             fechaInicioReestructura: Date,
//             fechaMasAntiguaHistoricoCAN: Date,
//             fechaMasAntiguaHistoricoPagos: Date,
//             fechaMasRecienteHistoricoCAN: Date,
//             fechaMasRecienteHistoricoPagos: Date,
//             fechaReporte: Date,
//             fechaUltimaCompra: Date,
//             fechaUltimoPago: Date,
//             formaPagoActual: string,
//             frecuenciaPagos: string,
//             garantia: string,
//             historicoCAN: string,
//             historicoPagos: string,
//             identificadorCAN: string,
//             identificadorDeCredito: string,
//             identificadorSociedadInformacionCrediticia: string,
//             importeSaldoMorosidadHistMasGrave: number // Defaults to 0
//             indicadorTipoResponsabilidad: string,
//             limiteCredito: number // Defaults to 0
//             modoReportar: string,
//             montoPagar: number // Defaults to 0
//             montoUltimoPago: string,
//             mopHistoricoMorosidadMasGrave: string,
//             nombreOtorgante: string,
//             numeroCuentaActual: string,
//             numeroPagos: number // Defaults to 0
//             numeroPagosVencidos: number
//             numeroTelefonoOtorgante: string,
//             registroImpugnado: string,
//             saldoActual: number,
//             saldoVencido: number,
//             tipoContrato: string,
//             tipoCuenta: string,
//             totalPagosCalificadosMOP2: number,
//             totalPagosCalificadosMOP3: number,
//             totalPagosCalificadosMOP4: number,
//             totalPagosCalificadosMOP5: number,
//             totalPagosReportados: number,
//             ultimaFechaSaldoCero: string,
//             valorActivoValuacion: string,
//         }],
//         declaracionesCliente: {
//             declaracionConsumidor: string
//         },
//         domicilios: [{
//             CP: string,
//             ciudad: string,
//             coloniaPoblacion: string,
//             delegacionMunicipio: string,
//             direccion1: string,
//             direccion2: string,
//             estado: string,
//             extension: string,
//             fax: string,
//             fechaReporteDireccion: Date,
//             fechaResidencia: Date,
//             indicadorEspecialDomicilio: string,
//             numeroTelefono: string,
//             origenDelDomicilio: string,
//             tipoDomicilio: string,
//         }],
//         empleos: [{
//             CP: string,
//             baseSalarial: string,
//             cargo: string,
//             ciudad: string,
//             claveMonedaSalario: string,
//             coloniaPoblacion: string,
//             delegacionMunicipio: string,
//             direccion1: string,
//             direccion2: string,
//             estado: string,
//             fax: string,
//             fechaContratacion: string,
//             fechaReportoEmpleo: string,
//             fechaUltimoDiaEmpleo: string,
//             fechaVerificacion: string,
//             modoVerificacion: string,
//             nombreEmpresa: string,
//             numeroTelefono: string,
//             origenRazonSocial: string,
//             salario: string
//         }],
//         encabezado: {
//             claveOtorgante: string,
//             clavePais: string,
//             claveRetornoConsumidorPrincipal: string,
//             numeroControlConsulta: number,
//             numeroReferenciaOperador: string, // Can send custom.
//             version: string,
//         },
//         hawkAlertBD: [{
//             codigoClave: string,
//             fechaReporte: string,
//             mensaje: string,
//             tipoInstitucion: string,
//         }],
//         hawkAlertConsulta: [{
//             codigoClave: string,
//             fechaReporte: string,
//             mensaje: string,
//             tipoInstitucion: string,
//         }],
//         historicoSaldos: [{
//             creditoMaximo: number,
//             fechaMaximaMorosidad: Date,
//             fechaReporte: Date,
//             fechaUltimaCompra: Date,
//             fechaUltimoPago: Date,
//             limiteCredito: number,
//             montoAPagar: number,
//             montoMaximoMorosidad: number,
//             montoUltimoPago: number,
//             mopMaximaMorosidad: string,
//             saldoActual: number,
//             saldoInsoluto: number,
//             saldoVencido: number,
//             ultimaVezSaldoCero: string,
//         }],
//         nombre: {
//             RFC: string,
//             apellidoAdicional: string,
//             apellidoMaterno: string,
//             apellidoPaterno: string,
//             clavePais: string,
//             curp: string,
//             edadesDependientes: string,
//             estadoCivil: string,
//             fechaDefuncion: Date,
//             fechaNacimiento: Date,
//             fechaRecepcionInformacionDependientes: string,
//             nacionalidad: string,
//             numeroCedulaProfesional: string,
//             numeroDependientes: string,
//             numeroLicenciaConducir: string,
//             numeroRegistroElectoral: string,
//             prefijo: string,
//             primerNombre: string,
//             residencia: string,
//             segundoNombre: string,
//             sexo: string,
//             sufijo: string,
//         },
//         resumenReporte: [{
//             cuentasCerradas: number,
//             cuentasClavesHistoriaNegativa: number,
//             cuentasDisputa: number,
//             cuentasNegativasActuales: number,
//             cuentasPagosFijosHipotecas: number,
//             cuentasRevolventesAbiertas: number,
//             existenciaDeclaracionesConsumidor: string,
//             fechaAperturaCuentaMRDespachoCobranza: string,
//             fechaApeturaCuentaMasAntigua: string,
//             fechaAperturaCuentaMasReciente: string,
//             fechaIngresoBD: string,
//             fechaSolicitudMasRecienteDespachoCobranza: string,
//             fechaSolicitudReporteMasReciente: string,
//             mensajesAlerta: string,
//             nuevaDireccionReportadaUltimos60Dias: string,
//             numeroCuentas: number,
//             numeroMOP0: string,
//             numeroMOP1: string,
//             numeroMOP2: string,
//             numeroMOP3: string,
//             numeroMOP4: string,
//             numeroMOP5: string,
//             numeroMOP6: string,
//             numeroMOP7: string,
//             numeroMOP96: string,
//             numeroMOP97: string,
//             numeroMOP99: string,
//             numeroMOPUR: string,
//             numeroSolicitudesUltimos6Meses: number,
//             numeroTotalCuentasDespachoCobranza: number,
//             numeroTotalSolicitudesDespachosCobranza: number,
//             pctLimiteCreditoUtilizadoRevolventes: number,
//             tipoMoneda: string,
//             totalCreditosMaximosPagosFijos: number,
//             totalCreditosMaximosRevolventes: number,
//             totalLimitesCreditoRevolventes: number,
//             totalPagosPagosFijos: number,
//             totalPagosRevolventes: number,
//             totalSaldosActualesPagosFijos: number,
//             totalSaldosActualesRevolventes: number,
//             totalSaldosVencidosPagosFijos: number,
//             totalSaldosVencidosRevolventes: number,
//             totalSolicitudesReporte: number,
//         }],
//         scoreBuroCredito: [{
//             codigoRazon1: string,
//             codigoRazon2: string,
//             codigoRazon3: string,
//             codigoScore: string,
//             nombreScore: string,
//             valorScore: number
//         }]
//     }
// }

interface Response {
   
    consultasEfectudas: [{
        claveOtorgante: string,
        claveUnidadMonetaria: string,
        consumidorNuevo: string,
        fechaConsulta: Date,
        identificacionBuro: string,
        importeContrato: number, // Defaults to 0
        indicadorTipoResponsabilidad: string,
        nombreOtorgante: string,
        telefonoOtorgante: string,
        tipoContrato: string,           
    }],
    cuentas: [{
        claveObservacion: string,
        claveOtorgante: string,
        claveUnidadMonetaria: string,
        creditoMaximo: number,
        fechaActualizacion: Date,
        fechaAperturaCuenta: Date,
        fechaCancelacionCAN: Date,
        fechaCierreCuenta: Date,
        fechaHistoricaMorosidadMasGrave: Date,
        fechaInicioReestructura: Date,
        fechaMasAntiguaHistoricoCAN: Date,
        fechaMasAntiguaHistoricoPagos: Date,
        fechaMasRecienteHistoricoCAN: Date,
        fechaMasRecienteHistoricoPagos: Date,
        fechaReporte: Date,
        fechaUltimaCompra: Date,
        fechaUltimoPago: Date,
        formaPagoActual: string,
        frecuenciaPagos: string,
        garantia: string,
        historicoCAN: string,
        historicoPagos: string,
        identificadorCAN: string,
        identificadorDeCredito: string,
        identificadorSociedadInformacionCrediticia: string,
        importeSaldoMorosidadHistMasGrave: number // Defaults to 0
        indicadorTipoResponsabilidad: string,
        limiteCredito: number // Defaults to 0
        modoReportar: string,
        montoPagar: number // Defaults to 0
        montoUltimoPago: string,
        mopHistoricoMorosidadMasGrave: string,
        nombreOtorgante: string,
        numeroCuentaActual: string,
        numeroPagos: number // Defaults to 0
        numeroPagosVencidos: number
        numeroTelefonoOtorgante: string,
        registroImpugnado: string,
        saldoActual: number,
        saldoVencido: number,
        tipoContrato: string,
        tipoCuenta: string,
        totalPagosCalificadosMOP2: number,
        totalPagosCalificadosMOP3: number,
        totalPagosCalificadosMOP4: number,
        totalPagosCalificadosMOP5: number,
        totalPagosReportados: number,
        ultimaFechaSaldoCero: string,
        valorActivoValuacion: string,
    }],
    declaracionesCliente: {
        declaracionConsumidor: string
    },
    domicilios: [{
        CP: string,
        ciudad: string,
        coloniaPoblacion: string,
        delegacionMunicipio: string,
        direccion1: string,
        direccion2: string,
        estado: string,
        extension: string,
        fax: string,
        fechaReporteDireccion: Date,
        fechaResidencia: Date,
        indicadorEspecialDomicilio: string,
        numeroTelefono: string,
        origenDelDomicilio: string,
        tipoDomicilio: string,
    }],
    empleos: [{
        CP: string,
        baseSalarial: string,
        cargo: string,
        ciudad: string,
        claveMonedaSalario: string,
        coloniaPoblacion: string,
        delegacionMunicipio: string,
        direccion1: string,
        direccion2: string,
        estado: string,
        fax: string,
        fechaContratacion: string,
        fechaReportoEmpleo: string,
        fechaUltimoDiaEmpleo: string,
        fechaVerificacion: string,
        modoVerificacion: string,
        nombreEmpresa: string,
        numeroTelefono: string,
        origenRazonSocial: string,
        salario: string
    }],
    encabezado: {
        claveOtorgante: string,
        clavePais: string,
        claveRetornoConsumidorPrincipal: string,
        numeroControlConsulta: number,
        numeroReferenciaOperador: string, // Can send custom.
        version: string,
    },
    hawkAlertBD: [{
        codigoClave: string,
        fechaReporte: string,
        mensaje: string,
        tipoInstitucion: string,
    }],
    hawkAlertConsulta: [{
        codigoClave: string,
        fechaReporte: string,
        mensaje: string,
        tipoInstitucion: string,
    }],
    historicoSaldos: [{
        creditoMaximo: number,
        fechaMaximaMorosidad: Date,
        fechaReporte: Date,
        fechaUltimaCompra: Date,
        fechaUltimoPago: Date,
        limiteCredito: number,
        montoAPagar: number,
        montoMaximoMorosidad: number,
        montoUltimoPago: number,
        mopMaximaMorosidad: string,
        saldoActual: number,
        saldoInsoluto: number,
        saldoVencido: number,
        ultimaVezSaldoCero: string,
    }],
    nombre: {
        RFC: string,
        apellidoAdicional: string,
        apellidoMaterno: string,
        apellidoPaterno: string,
        clavePais: string,
        curp: string,
        edadesDependientes: string,
        estadoCivil: string,
        fechaDefuncion: Date,
        fechaNacimiento: Date,
        fechaRecepcionInformacionDependientes: string,
        nacionalidad: string,
        numeroCedulaProfesional: string,
        numeroDependientes: string,
        numeroLicenciaConducir: string,
        numeroRegistroElectoral: string,
        prefijo: string,
        primerNombre: string,
        residencia: string,
        segundoNombre: string,
        sexo: string,
        sufijo: string,
    },
    resumenReporte: [{
        cuentasCerradas: number,
        cuentasClavesHistoriaNegativa: number,
        cuentasDisputa: number,
        cuentasNegativasActuales: number,
        cuentasPagosFijosHipotecas: number,
        cuentasRevolventesAbiertas: number,
        existenciaDeclaracionesConsumidor: string,
        fechaAperturaCuentaMRDespachoCobranza: string,
        fechaApeturaCuentaMasAntigua: string,
        fechaAperturaCuentaMasReciente: string,
        fechaIngresoBD: string,
        fechaSolicitudMasRecienteDespachoCobranza: string,
        fechaSolicitudReporteMasReciente: string,
        mensajesAlerta: string,
        nuevaDireccionReportadaUltimos60Dias: string,
        numeroCuentas: number,
        numeroMOP0: string,
        numeroMOP1: string,
        numeroMOP2: string,
        numeroMOP3: string,
        numeroMOP4: string,
        numeroMOP5: string,
        numeroMOP6: string,
        numeroMOP7: string,
        numeroMOP96: string,
        numeroMOP97: string,
        numeroMOP99: string,
        numeroMOPUR: string,
        numeroSolicitudesUltimos6Meses: number,
        numeroTotalCuentasDespachoCobranza: number,
        numeroTotalSolicitudesDespachosCobranza: number,
        pctLimiteCreditoUtilizadoRevolventes: number,
        tipoMoneda: string,
        totalCreditosMaximosPagosFijos: number,
        totalCreditosMaximosRevolventes: number,
        totalLimitesCreditoRevolventes: number,
        totalPagosPagosFijos: number,
        totalPagosRevolventes: number,
        totalSaldosActualesPagosFijos: number,
        totalSaldosActualesRevolventes: number,
        totalSaldosVencidosPagosFijos: number,
        totalSaldosVencidosRevolventes: number,
        totalSolicitudesReporte: number,
    }],
    scoreBuroCredito: [{
        codigoRazon1: string,
        codigoRazon2: string,
        codigoRazon3: string,
        codigoScore: string,
        nombreScore: string,
        valorScore: number
    }]
 
}

export interface BuroFisicaReporte extends Response {

}